---
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: 1000:1000
    ports:
      - 8081:80 #default port is 8080, change as needed. Don't change port 80
    volumes:
      - /home/user:/srv #change 'user' for both volume entries to your name
      - /home/user/appdata/filebrowser/filebrowser.db:/database.db #create the filebrowser.db file before deploying
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
