version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser
    user: 1000:1000
    ports:
      - 8081:80
    volumes:
      - /home/user:/srv #change user to your name or use ~/
      - /home/user/appdata/filebrowser/filebrowser.db:/database.db #create the filebrowser.db file before deploying
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
